### ISSUE TITLE
MPRIS album artwork not updating

### ISSUE THREAD

**Issue by therealfumbles** [fooyin/fooyin#145] opened 2024-06-18 12:24 UTC
**Describe the bug**
The artwork for the first-played track is always displayed via MPRIS.

**To Reproduce**
Play two or more tracks from different artists/albums. This will even persist if I close and re-open the app.

**Expected behaviour**
Artwork should update with track details.

**System:**
 - OS:  debian sid / Gnome / Wayland
 - fooyin version: 0.4.5

**Additional context**
Initially I installed fooyin via flatpak as that's where I found it. I've since installed the 0.4.5 from the releases page and the latest artifact from Actions and the behaviour is the same.

Until now I've been using Strawberry and it displays artwork correctly via MPRIS so I think that rules out any issue with my system.

Thanks so much for making this. I've missed foobar2000 since moving to linux and this ticks a lot of the boxes missing in the other players I've tried.

**Comment by ludouzi** [comment] 2024-06-18 13:35
Thanks. Looks like the artwork path passed to MPRIS is cached and as we use the same path for all MPRIS artwork (and only update the image data), it doesn't always detect changes. Fixing should be as simple as saving to a unique path.

**Comment by ludouzi** [comment] 2024-06-18 16:13
This should now be fixed with https://github.com/fooyin/fooyin/commit/ed1a3d1bf988dce6564ce16ed935ca891c599b5c. If not, it may be related to how the artwork key is generated (using metadata and parts of the track's filepath).

**Comment by therealfumbles** [comment] 2024-06-18 16:35
Thanks for the quick fix. I installed the latest artifact and the artwork is updating correctly now :)

I'm running into other weird behavior with some files when using the native deb installers that I don't get with the flatpak version. Maybe it's something with my system (as it's sid, not trixie) so I'm gonna stick with the flatpak version for the time being. It also makes it easy to see when there's a new release.

**Comment by ludouzi** [comment] 2024-06-18 16:41
What sort of weird behaviour are you seeing? There's been a lot of changes under the hood to support CUE sheets so it may be related to that more than differences in packaging.

**Comment by therealfumbles** [comment] 2024-06-18 16:59
There's one 18-track flac album that loads all but the last track as 0 second tracks, doesn't load the second track and lists the last track twice. The last track plays fine but as all the others are 0 sec it's the only one that plays.

Wondering if it was a cue file issue, I tried dragging just the flacs into the playlist from a file browser window instead of from the library tree and it did the same thing.

Also, my iTunes store m4a files display 0 ch in the status bar instead of Stereo. Running fooyin from the terminal it also prints warnings like this for them:

[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f33700022c0] Detected creation time before 1970, parsing as unix timestamp.
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f33700022c0] stream 0, timescale not set

Neither of these playback issue happen with the flatpak version.

**Comment by ludouzi** [comment] 2024-06-18 17:06
Thanks, I'll look into all of those issues.

**Comment by therealfumbles** [comment] 2024-07-01 15:45
Hi I've just switched back to the deb installer from flatpak. Running the latest artifact I can confirm that the m4a issue is fixed. When launched from the terminal it still prints the same messages but correctly shows Stereo instead of 0ch.

The flac album one is behaving even weirder now. 

If  I drag the album folder to a new playlist from the library it loads all the tracks fine, but also appends an equal amount of copies of a U2 track:

![Screenshot from 2024-07-01 16-35-56](https://github.com/fooyin/fooyin/assets/86084089/11780ef3-3236-48ab-af18-92cb9946551f)

If I restart fooyin and drag just the flacs from the album instead of the album folder itself then no extra tracks appear. However if I try this after dragging the folder it will still insert the U2 track except it will add one instance after each track in the album:

![Screenshot from 2024-07-01 16-44-39](https://github.com/fooyin/fooyin/assets/86084089/68bf4931-f3d8-4ac4-af34-a46f81b734c7)

I've attached the cue file in case it might have some clues.

[Sam - Synthetic Adrenaline Music.cue.txt](https://github.com/user-attachments/files/16055656/Sam.-.Synthetic.Adrenaline.Music.cue.txt)

**Comment by ludouzi** [comment] 2024-07-01 16:16
Thanks for providing the cue file. I've just tested it by replacing the file names with some of my own files and it looks like it's working when dragging just the cue file and just dragging the files.

A possible cause of the problem is the database holding invalid cue paths for some files from when you had issues earlier. This will be fairly easy to test.

Could you try renaming the database file `~/.local/share/fooyin/fooyin.db` and starting fooyin with a new one?

**Comment by therealfumbles** [comment] 2024-07-01 16:44
Yep that fixed it! 

I have a lot of albums spread across four directories so I tried to save time by copying the db file over from the flatpak install.

**Closed** 2024-08-16 23:07 UTC
Labels: bug
