### ISSUE TITLE
No tray icon in Flatpak version

### ISSUE THREAD

**Issue by iamalexei** [fooyin/fooyin#373] opened 2024-10-29 15:21 UTC
**Describe the bug**
When I launch Fooyin there's no tray icon. Also the "Show system tray icon" and "Minimize to tray on close" settings are greyed out.

**To Reproduce**
1. Install fooyin from Flathub
2. Launch fooyin
3. Open Settings > General

**Expected behaviour**
"Show system tray icon" and "Minimize to tray on close" check boxes should not be greyed out and fooyin should allow to enable or disable them. When "Show system tray icon" is enabled fooyin should show the tray icon.

**System:**
 - OS: Debian 12.7
 - fooyin version: 0.8.1, Based on Qt 6.7.3 (GCC 13.2.0, x86_64)

**Comment by ludouzi** [comment] 2024-10-29 15:36
Looks like this is caused by a lack of permissions in the flatpak build. I'll have it fixed for the next release.

In the meantime, it can be fixed by using the override: `flatpak override org.fooyin.fooyin --talk-name=org.kde.StatusNotifierWatcher`. 

Alternatively, you can use [Flatseal](https://github.com/tchx84/Flatseal) to enable `D-Bus session bus`.

**Comment by iamalexei** [comment] 2024-10-29 15:51
@ludouzi thank you! Your `flatpak override` workaround helped

**Closed** 2024-11-14 01:35 UTC
