### ISSUE TITLE
link time fails with many undefined symbol errors when building with -DBUILD_ASAN=ON

### ISSUE THREAD

**Issue by unhappy-ending** [fooyin/fooyin#124] opened 2024-05-29 15:47 UTC
My system is Gentoo built with Clang, LLD, the LLVM toolchain, and LLVM libc++, libunwind, and runtimes. I've tried passing -fuse-ld=bfd and ended up with similar undefined symbol errors. I'm including both build logs for each linker.

LLD will output a lot of `error: undefined symbol: __asan_*` and `error: undefined symbol: __ubsan_*`

[fooyin-0.4.3:20240529-111210.log](https://github.com/ludouzi/fooyin/files/15486869/fooyin-0.4.3.20240529-111210.log)

BFD will output a lot of `undefined reference to __asan_*` and `undefined reference to __ubsan_*`

[fooyin-0.4.3:20240529-112702.log](https://github.com/ludouzi/fooyin/files/15486871/fooyin-0.4.3.20240529-112702.log)

I decided to try building with `-DBUILD_ASAN=OFF` and passing `-fsanitize=address,undefined` separately from each other.

`-fsanitize=address` successfully compiles
`-fsanitize=undefined` successfully compiles

Out of curiosity I also tried `-DBUILD_ASAN=OFF` and passing `-fsanitize=address,undefined` together as it would be via the cmake option.

`-fsanitize=address,undefined` successfully compiles

?? Not sure what's going on here. Any other info I can supply let me know.

**Comment by ludouzi** [comment] 2024-05-30 12:46
All `BUILD_ASAN` does is add `fsanitize=address,undefined` to the compile options for each target, so I'm not sure why it's behaving differently to passing it separately from outside.

I'm going to try and reproduce in a similar system.

**Comment by ludouzi** [comment] 2024-05-30 13:15
Looks like the link options were mistakenly removed in an earlier commit. Should be fixed with https://github.com/ludouzi/fooyin/commit/c76142f3cba6431012d20211f158a9b1d75c0928.

**Comment by unhappy-ending** [comment] 2024-05-31 07:05
Thank you, just tested it the commit out and everything compiles fine here!

**Closed** 2024-06-20 11:35 UTC
