### ISSUE TITLE
"Auto track number" tool tags incorrectly

### ISSUE THREAD

**Issue by therealfumbles** [fooyin/fooyin#214] opened 2024-08-07 20:01 UTC
In trying to convert an album from aif to flac I first converted the files with flac but this left me with no tags.

I tried to do as in foobar and batch copy/paste the tags from the source files in one playlist to the new files in another playlist but this didn't work. There's no option to copy or paste tags into the metadata page yet.

So I clicked on the auto track number tool to make a bit of a start but instead of tagging the files 1-10 it tagged them 1, 10, 2, 3, 4, 5, 6, 7, 8, 9.

**Comment by ludouzi** [comment] 2024-08-07 20:10
That's probably due the recent change to support alphanumeric track numbers. I'll look into it now.

**Comment by ludouzi** [comment] 2024-08-07 20:36
I was able to reproduce this by selecting the tracks out of order, so it may be related to how the tracks are selected before opening properties.

**Comment by therealfumbles** [comment] 2024-08-07 21:30
I was selecting the tracks from the playlist properties. But now I see it happens there too.

Drag an album to a new playlist, right click on the playlist tab and select properties. In the metadata window that opens you'll see that it goes from track 1 to track 10+ and then 2+.

**Comment by ludouzi** [comment] 2024-08-07 21:57
Ah, I think I see where the problem is.

The metadata field values are not displayed in track order but are sorted using QCollator. If Qt is compiled without ICU support (which is the case for some distros), then it will sort numbers in ASCII-order i.e. 100 comes before 2.

With https://github.com/fooyin/fooyin/commit/3edc4a37c9283cc350221e68f44b5003da6cf339, I've removed the sorting of values which may help in that case.

**Comment by therealfumbles** [comment] 2024-08-07 22:06
Yep that's fixed the sorting order now!

**Comment by therealfumbles** [comment] 2024-08-07 23:16
Actually, it's still sorting incorrectly in the Details tab (Track Number value).

**Comment by therealfumbles** [comment] 2024-08-08 15:55
Thanks for the fix. Now it all displays fine.

I noticed you also added copy/paste functions in the metadata pages. This is a big help but currently has some issues:

1) Custom metadata tags are not pasted into the right value. For example, if I select all the metadata for a song and copy it to a destination file, any tags that are non-standard (listed at the end) will have their values pasted into (presumably) the first available slot rather than into a new custom tag.

2) Batch copying/pasting doesn't work at all. Tags containing multiple values are pasted as-is into every file.

I might be jumping ahead a little here as this might be work you plan to do down the line. But I figured I'd mention them.

**Comment by ludouzi** [comment] 2024-08-08 17:58
Thanks for testing. Yeah, it's still a work-in-progress, but the above issues should be resolved with https://github.com/fooyin/fooyin/commit/daf84bfe8279d5a9f5e94525d6c820c0ac99747f. 

It's currently designed the same as foobar, so pasting over a selection will paste in order, but pasting fields (a separate action) will copy over the fields which match (and add all extra tags).

**Comment by therealfumbles** [comment] 2024-08-08 18:14
Thanks for working some more on this. 

#1 is kinda fixed in that it just drops any custom tags rather than pasting them into the wrong place.

#2 now correctly pastes from multiple sources to multiple destinations but also drops any custom tags.

**Comment by ludouzi** [comment] 2024-08-08 19:25
Are you using the 'Paste Fields' action? As mentioned above, that will copy all fields (including custom tags), while pasting over a selection will just overwrite the selected rows.

**Comment by therealfumbles** [comment] 2024-08-08 19:34
Yep. I've tried paste and paste fields. 

On closer inspection, paste fields seems to work, but when I hit apply/ok the extra tag field name is cleared out and the tag disappears once I check the file again. So perhaps it's being sanitised on save?

**Comment by ludouzi** [comment] 2024-08-08 20:44
Thanks. Turns out it was being sanitised.

**Comment by therealfumbles** [comment] 2024-08-08 21:04
It's not being sanitised anymore, but if I copy/paste multiple tags the extra tag contains all the tags instead of applying each one to the correct file.

When I select multiple files to copy (usually I just select the playlist) it shows <<multiple values>> for the contents of the extra tag but when I paste (paste fields) the <<multiple values>> bit is missing and all the tag values are written to each file.

**Comment by therealfumbles** [comment] 2024-08-08 21:56
I just checked b1bef64 and now all values are pasting correctly. Thanks for getting all this working so quickly!

**Closed** 2024-08-16 23:04 UTC
Labels: bug
