### ISSUE TITLE
Track finishing and then continuning to play silence while the timer is still going up

### ISSUE THREAD

**Issue by OrangeRollo** [fooyin/fooyin#229] opened 2024-08-17 10:04 UTC
**Describe the bug**
Occasionally I will be listening to playlist and it will finish a song in the playlist and keep playing silence while the counting up above the track time finish. I have to manually change the track to stop it.

i.e. The track is 3:30 long. It will get to the end of the track and start counting up above 3:30 while not playing anything.

**To Reproduce**
Unfortunately I can't find a standard way to reproduce this. The times it has happened have been while it is in the background and not in focus.

**System:**
 - OS: EndeavorOS (Arch)
 - fooyin version: 0.5.3 (fooyin-git from AUR)

**Additional context**
Is there anything specific I can make note of if/when it happens again?

**Comment by ludouzi** [comment] 2024-08-17 13:46
This sounds like a race condition where the finished signal isn't received from the audio renderer once it hits the end of file buffer. Another possibility is the decoder not doing the same.

I'll add a few log messages to help debug this.

**Comment by ludouzi** [comment] 2024-08-17 14:09
With https://github.com/fooyin/fooyin/commit/fc3dcfb88e740b52e9082f92c9d1297adbd6ecc0 you can enable debug level messages in `View->Log` which will really help with identifying the cause if it happens again.

**Comment by 23365209** [comment] 2024-08-17 21:03
This also happened to me.
You can reproduce it by: Playing any song -> Pausing -> Playing again

**Comment by ludouzi** [comment] 2024-08-17 21:19
Hmm. Do you have fading enabled?

**Comment by 23365209** [comment] 2024-08-17 21:46
Nope, I do not have fading enabled.
But after recording the video below I turned it on and now it changes track when the one currently playing finishes.


https://github.com/user-attachments/assets/f285759f-b4aa-408e-ade0-3d4da53f89ec

**Comment by ludouzi** [comment] 2024-08-17 21:49
Thanks for the info. This should be resolved with https://github.com/fooyin/fooyin/commit/0c204a3aadaccd0c0330fbac1304adbac37da7fc.

**Comment by 23365209** [comment] 2024-08-19 10:43
I have been playing music from playlists and my library and this hasn't happened again so that seems to have fixed it.
Thank you.

**Comment by OrangeRollo** [comment] 2024-08-19 12:19
Thanks. I can conform the fix too.

**Closed** 2024-08-19 16:15 UTC
Labels: bug
